// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartFactory.Api.Data;

#nullable disable

namespace SmartFactory.Api.Migrations
{
    [DbContext(typeof(SmartFactoryDbContext))]
    [Migration("20260721072845_AddCamerasAndAppSettings")]
    partial class AddCamerasAndAppSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartFactory.Api.Models.Database.AiRecommendationEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("created_at");

                    b.Property<string>("ExpectedImpact")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("expected_impact");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("module");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reason");

                    b.Property<string>("ReviewedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("reviewed_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_ai_recommendations");

                    b.HasIndex("ReviewedBy")
                        .HasDatabaseName("ix_ai_recommendations_reviewed_by");

                    b.ToTable("ai_recommendations", (string)null);
                });

            modelBuilder.Entity("SmartFactory.Api.Models.Database.AiRecommendationLinkEntity", b =>
                {
                    b.Property<string>("RecommendationId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("recommendation_id");

                    b.Property<string>("EntityType")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("entity_type");

                    b.Property<string>("EntityId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("entity_id");

                    b.Property<string>("LinkReason")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("link_reason");

                    b.HasKey("RecommendationId", "EntityType", "EntityId")
                        .HasName("pk_ai_recommendation_links");

                    b.ToTable("ai_recommendation_links", (string)null);
                });

            modelBuilder.Entity("SmartFactory.Api.Models.Database.AppSettingEntity", b =>
                {
                    b.Property<string>("SettingKey")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("setting_key");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("description");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("setting_value");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("updated_at");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("value_type");

                    b.HasKey("SettingKey")
                        .HasName("pk_app_settings");

                    b.ToTable("app_settings", (string)null);
                });

            modelBuilder.Entity("SmartFactory.Api.Models.Database.BusinessUnitEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("id");

                    b.Property<string>("BuCode")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("bu_code");

                    b.Property<string>("BuName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("bu_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_business_units");

                    b.HasIndex("BuCode")
                        .IsUnique()
                        .HasDatabaseName("ix_business_units_bu_code");

                    b.ToTable("business_units", (string)null);
                });

            modelBuilder.Entity("SmartFactory.Api.Models.Database.CameraEntity", b =>
                {
                    b.Property<string>("CameraCode")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("camera_code");

                    b.Property<string>("AreaId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("area_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("status");

                    b.HasKey("CameraCode")
                        .HasName("pk_cameras");

                    b.HasIndex("AreaId")
                        .HasDatabaseName("ix_cameras_area_id");

                    b.ToTable("cameras", (string)null);
                });

            modelBuilder.Entity("SmartFactory.Api.Models.Database.CameraEventEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("id");

                    b.Property<string>("AreaId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("area_id");

                    b.Property<string>("CameraCode")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("camera_code");

                    b.Property<double>("Confidence")
                        .HasColumnType("float")
                        .HasColumnName("confidence");

                    b.Property<string>("EventTime")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("event_time");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("event_type");

                    b.Property<string>("RelatedAlertId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("related_alert_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("severity");

                    b.HasKey("Id")
                        .HasName("pk_camera_events");

                    b.HasIndex("AreaId")
                        .HasDatabaseName("ix_camera_events_area_id");

                    b.HasIndex("RelatedAlertId")
                        .HasDatabaseName("ix_camera_events_related_alert_id");

                    b.ToTable("camera_events", (string)null);
                });

            modelBuilder.Entity("SmartFactory.Api.Models.Database.EmployeeEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("id");

                    b.Property<string>("AvailabilityStatus")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("availability_status");

                    b.Property<string>("CurrentLineId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("current_line_id");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("department");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("employee_code");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("full_name");

                    b.Property<string>("SkillTags")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("skill_tags");

                    b.HasKey("Id")
                        .HasName("pk_employees");

                    b.HasIndex("CurrentLineId")
                        .HasDatabaseName("ix_employees_current_line_id");

                    b.HasIndex("EmployeeCode")
                        .IsUnique()
                        .HasDatabaseName("ix_employees_employee_code");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("SmartFactory.Api.Models.Database.EmployeeSkillEntity", b =>
                {
                    b.Property<string>("EmployeeId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("employee_id");

                    b.Property<string>("SkillId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("skill_id");

                    b.Property<string>("CertifiedAt")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("certified_at");

                    b.Property<string>("ExpiresAt")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("expires_at");

                    b.Property<string>("ProficiencyLevel")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("proficiency_level");

                    b.HasKey("EmployeeId", "SkillId")
                        .HasName("pk_employee_skills");

                    b.HasIndex("SkillId")
                        .HasDatabaseName("ix_employee_skills_skill_id");

                    b.ToTable("employee_skills", (string)null);
                });

            modelBuilder.Entity("SmartFactory.Api.Models.Database.FactoryAreaEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("id");

                    b.Property<string>("AreaType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("area_type");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("name");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("risk_level");

                    b.HasKey("Id")
                        .HasName("pk_factory_areas");

                    b.ToTable("factory_areas", (string)null);
                });

            modelBuilder.Entity("SmartFactory.Api.Models.Database.FormApprovalStepEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("id");

                    b.Property<string>("ActionAt")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("action_at");

                    b.Property<string>("ApproverId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("approver_id");

                    b.Property<string>("FormId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("form_id");

                    b.Property<string>("Note")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("status");

                    b.Property<int>("StepOrder")
                        .HasColumnType("int")
                        .HasColumnName("step_order");

                    b.HasKey("Id")
                        .HasName("pk_form_approval_steps");

                    b.HasIndex("ApproverId")
                        .HasDatabaseName("ix_form_approval_steps_approver_id");

                    b.HasIndex("FormId")
                        .HasDatabaseName("ix_form_approval_steps_form_id");

                    b.ToTable("form_approval_steps", (string)null);
                });

            modelBuilder.Entity("SmartFactory.Api.Models.Database.FormRequestEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("id");

                    b.Property<string>("ApprovedAt")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("approved_at");

                    b.Property<string>("ApproverId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("approver_id");

                    b.Property<string>("FormType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("form_type");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("RequesterId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("requester_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("status");

                    b.Property<string>("SubmittedAt")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("submitted_at");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("summary");

                    b.HasKey("Id")
                        .HasName("pk_form_requests");

                    b.HasIndex("ApproverId")
                        .HasDatabaseName("ix_form_requests_approver_id");

                    b.HasIndex("RequesterId")
                        .HasDatabaseName("ix_form_requests_requester_id");

                    b.ToTable("form_requests", (string)null);
                });

            modelBuilder.Entity("SmartFactory.Api.Models.Database.GoodsMovementEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("id");

                    b.Property<string>("FromZoneId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("from_zone_id");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("item_id");

                    b.Property<string>("MovedAt")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("moved_at");

                    b.Property<string>("MovedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("moved_by");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("movement_type");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<string>("ToZoneId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("to_zone_id");

                    b.HasKey("Id")
                        .HasName("pk_goods_movements");

                    b.HasIndex("FromZoneId")
                        .HasDatabaseName("ix_goods_movements_from_zone_id");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_goods_movements_item_id");

                    b.HasIndex("MovedBy")
                        .HasDatabaseName("ix_goods_movements_moved_by");

                    b.HasIndex("ToZoneId")
                        .HasDatabaseName("ix_goods_movements_to_zone_id");

                    b.ToTable("goods_movements", (string)null);
                });

            modelBuilder.Entity("SmartFactory.Api.Models.Database.IoMasterEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("id");

                    b.Property<string>("BuId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("bu_id");

                    b.Property<string>("IoCode")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("io_code");

                    b.Property<string>("IoId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("io_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_io_masters");

                    b.HasIndex("BuId")
                        .HasDatabaseName("ix_io_masters_bu_id");

                    b.HasIndex("IoCode")
                        .IsUnique()
                        .HasDatabaseName("ix_io_masters_io_code");

                    b.HasIndex("IoId")
                        .IsUnique()
                        .HasDatabaseName("ix_io_masters_io_id");

                    b.ToTable("io_masters", (string)null);
                });

            modelBuilder.Entity("SmartFactory.Api.Models.Database.MachineEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("id");

                    b.Property<string>("LastMaintenanceAt")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("last_maintenance_at");

                    b.Property<string>("LineId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("line_id");

                    b.Property<string>("MachineCode")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("machine_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_machines");

                    b.HasIndex("LineId")
                        .HasDatabaseName("ix_machines_line_id");

                    b.HasIndex("MachineCode")
                        .IsUnique()
                        .HasDatabaseName("ix_machines_machine_code");

                    b.ToTable("machines", (string)null);
                });

            modelBuilder.Entity("SmartFactory.Api.Models.Database.MachineIssueEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("LineId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("line_id");

                    b.Property<string>("MachineId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("machine_id");

                    b.Property<string>("ReportedAt")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("reported_at");

                    b.Property<string>("ReportedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("reported_by");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_machine_issues");

                    b.HasIndex("LineId")
                        .HasDatabaseName("ix_machine_issues_line_id");

                    b.HasIndex("MachineId")
                        .HasDatabaseName("ix_machine_issues_machine_id");

                    b.HasIndex("ReportedBy")
                        .HasDatabaseName("ix_machine_issues_reported_by");

                    b.ToTable("machine_issues", (string)null);
                });

            modelBuilder.Entity("SmartFactory.Api.Models.Database.NotificationEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("created_at");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("notification_type");

                    b.Property<string>("RelatedEntityId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("related_entity_id");

                    b.Property<string>("RelatedEntityType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("related_entity_type");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("status");

                    b.Property<string>("TargetUserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("target_user_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("TargetUserId")
                        .HasDatabaseName("ix_notifications_target_user_id");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("SmartFactory.Api.Models.Database.NotificationLinkEntity", b =>
                {
                    b.Property<string>("NotificationId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("notification_id");

                    b.Property<string>("EntityType")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("entity_type");

                    b.Property<string>("EntityId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("entity_id");

                    b.Property<string>("LinkRole")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("link_role");

                    b.HasKey("NotificationId", "EntityType", "EntityId")
                        .HasName("pk_notification_links");

                    b.ToTable("notification_links", (string)null);
                });

            modelBuilder.Entity("SmartFactory.Api.Models.Database.PermissionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("action");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("module");

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("permission_code");

                    b.HasKey("Id")
                        .HasName("pk_permissions");

                    b.HasIndex("PermissionCode")
                        .IsUnique()
                        .HasDatabaseName("ix_permissions_permission_code");

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("SmartFactory.Api.Models.Database.ProductionLineEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("id");

                    b.Property<int>("ActualOutput")
                        .HasColumnType("int")
                        .HasColumnName("actual_output");

                    b.Property<string>("AreaId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("area_id");

                    b.Property<int>("AssignedWorkers")
                        .HasColumnType("int")
                        .HasColumnName("assigned_workers");

                    b.Property<double>("DefectRate")
                        .HasColumnType("float")
                        .HasColumnName("defect_rate");

                    b.Property<int>("DowntimeMinutes")
                        .HasColumnType("int")
                        .HasColumnName("downtime_minutes");

                    b.Property<int>("Efficiency")
                        .HasColumnType("int")
                        .HasColumnName("efficiency");

                    b.Property<string>("Issue")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("issue");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("status");

                    b.Property<int>("TargetOutput")
                        .HasColumnType("int")
                        .HasColumnName("target_output");

                    b.HasKey("Id")
                        .HasName("pk_production_lines");

                    b.HasIndex("AreaId")
                        .HasDatabaseName("ix_production_lines_area_id");

                    b.ToTable("production_lines", (string)null);
                });

            modelBuilder.Entity("SmartFactory.Api.Models.Database.ProductionRecordEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("id");

                    b.Property<int>("ActualOutput")
                        .HasColumnType("int")
                        .HasColumnName("actual_output");

                    b.Property<int>("DefectCount")
                        .HasColumnType("int")
                        .HasColumnName("defect_count");

                    b.Property<int>("DowntimeMinutes")
                        .HasColumnType("int")
                        .HasColumnName("downtime_minutes");

                    b.Property<string>("LineId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("line_id");

                    b.Property<string>("RecordTime")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("record_time");

                    b.Property<int>("TargetOutput")
                        .HasColumnType("int")
                        .HasColumnName("target_output");

                    b.HasKey("Id")
                        .HasName("pk_production_records");

                    b.HasIndex("LineId")
                        .HasDatabaseName("ix_production_records_line_id");

                    b.ToTable("production_records", (string)null);
                });

            modelBuilder.Entity("SmartFactory.Api.Models.Database.ReportEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("created_by");

                    b.Property<string>("PeriodEnd")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("period_end");

                    b.Property<string>("PeriodStart")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("period_start");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("report_type");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_reports");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_reports_created_by");

                    b.ToTable("reports", (string)null);
                });

            modelBuilder.Entity("SmartFactory.Api.Models.Database.ReportSourceLinkEntity", b =>
                {
                    b.Property<string>("ReportId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("report_id");

                    b.Property<string>("SourceType")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("source_type");

                    b.Property<string>("SourceId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("source_id");

                    b.Property<string>("IncludedAt")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("included_at");

                    b.HasKey("ReportId", "SourceType", "SourceId")
                        .HasName("pk_report_source_links");

                    b.ToTable("report_source_links", (string)null);
                });

            modelBuilder.Entity("SmartFactory.Api.Models.Database.RoleEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_name");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("SmartFactory.Api.Models.Database.RolePermissionEntity", b =>
                {
                    b.Property<string>("RoleId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("role_id");

                    b.Property<string>("PermissionId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("permission_id");

                    b.Property<string>("GrantedAt")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("granted_at");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("pk_role_permissions");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_role_permissions_permission_id");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("SmartFactory.Api.Models.Database.SafetyAlertCameraEventEntity", b =>
                {
                    b.Property<string>("AlertId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("alert_id");

                    b.Property<string>("CameraEventId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("camera_event_id");

                    b.Property<string>("LinkedAt")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("linked_at");

                    b.Property<string>("RelationType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("relation_type");

                    b.HasKey("AlertId", "CameraEventId")
                        .HasName("pk_safety_alert_camera_events");

                    b.HasIndex("CameraEventId")
                        .HasDatabaseName("ix_safety_alert_camera_events_camera_event_id");

                    b.ToTable("safety_alert_camera_events", (string)null);
                });

            modelBuilder.Entity("SmartFactory.Api.Models.Database.SafetyAlertEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("id");

                    b.Property<string>("ActionNote")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("action_note");

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("alert_type");

                    b.Property<string>("AreaId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("area_id");

                    b.Property<string>("AssignedTo")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("assigned_to");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("DetectedAt")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("detected_at");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_safety_alerts");

                    b.HasIndex("AreaId")
                        .HasDatabaseName("ix_safety_alerts_area_id");

                    b.HasIndex("AssignedTo")
                        .HasDatabaseName("ix_safety_alerts_assigned_to");

                    b.ToTable("safety_alerts", (string)null);
                });

            modelBuilder.Entity("SmartFactory.Api.Models.Database.ShiftPlanAssignmentEntity", b =>
                {
                    b.Property<string>("ShiftId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("shift_id");

                    b.Property<string>("EmployeeId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("employee_id");

                    b.Property<string>("AssignedAt")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("assigned_at");

                    b.Property<string>("AssignmentRole")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("assignment_role");

                    b.Property<string>("AssignmentStatus")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("assignment_status");

                    b.HasKey("ShiftId", "EmployeeId")
                        .HasName("pk_shift_plan_assignments");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_shift_plan_assignments_employee_id");

                    b.ToTable("shift_plan_assignments", (string)null);
                });

            modelBuilder.Entity("SmartFactory.Api.Models.Database.ShiftPlanEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("id");

                    b.Property<int>("AssignedWorkers")
                        .HasColumnType("int")
                        .HasColumnName("assigned_workers");

                    b.Property<string>("LineId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("line_id");

                    b.Property<double>("OvertimeHours")
                        .HasColumnType("float")
                        .HasColumnName("overtime_hours");

                    b.Property<int>("RequiredWorkers")
                        .HasColumnType("int")
                        .HasColumnName("required_workers");

                    b.Property<string>("ShiftDate")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("shift_date");

                    b.Property<string>("ShiftName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("shift_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_shift_plans");

                    b.HasIndex("LineId")
                        .HasDatabaseName("ix_shift_plans_line_id");

                    b.ToTable("shift_plans", (string)null);
                });

            modelBuilder.Entity("SmartFactory.Api.Models.Database.SkillEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("id");

                    b.Property<string>("SkillCode")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("skill_code");

                    b.Property<string>("SkillGroup")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("skill_group");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("skill_name");

                    b.HasKey("Id")
                        .HasName("pk_skills");

                    b.HasIndex("SkillCode")
                        .IsUnique()
                        .HasDatabaseName("ix_skills_skill_code");

                    b.ToTable("skills", (string)null);
                });

            modelBuilder.Entity("SmartFactory.Api.Models.Database.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("created_at");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("department");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("full_name");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("role_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_users_role_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SmartFactory.Api.Models.Database.WarehouseItemEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("id");

                    b.Property<string>("BatchCode")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("batch_code");

                    b.Property<string>("Bu")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("bu");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("category");

                    b.Property<string>("IoCode")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("io_code");

                    b.Property<string>("IoId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("io_id");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("item_code");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("item_name");

                    b.Property<string>("LastMovementAt")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("last_movement_at");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<string>("Shelf")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("shelf");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("status");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("unit");

                    b.Property<string>("ZoneId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("zone_id");

                    b.HasKey("Id")
                        .HasName("pk_warehouse_items");

                    b.HasIndex("ItemCode")
                        .IsUnique()
                        .HasDatabaseName("ix_warehouse_items_item_code");

                    b.HasIndex("ZoneId")
                        .HasDatabaseName("ix_warehouse_items_zone_id");

                    b.ToTable("warehouse_items", (string)null);
                });

            modelBuilder.Entity("SmartFactory.Api.Models.Database.WarehouseItemIoLinkEntity", b =>
                {
                    b.Property<string>("ItemId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("item_id");

                    b.Property<string>("IoMasterId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("io_master_id");

                    b.Property<string>("EffectiveFrom")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("effective_from");

                    b.Property<string>("EffectiveTo")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("effective_to");

                    b.Property<string>("LinkType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("link_type");

                    b.HasKey("ItemId", "IoMasterId")
                        .HasName("pk_warehouse_item_io_links");

                    b.HasIndex("IoMasterId")
                        .HasDatabaseName("ix_warehouse_item_io_links_io_master_id");

                    b.ToTable("warehouse_item_io_links", (string)null);
                });

            modelBuilder.Entity("SmartFactory.Api.Models.Database.WarehouseZoneEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("id");

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("capacity");

                    b.Property<int>("CurrentUsage")
                        .HasColumnType("int")
                        .HasColumnName("current_usage");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("status");

                    b.Property<string>("ZoneType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("zone_type");

                    b.HasKey("Id")
                        .HasName("pk_warehouse_zones");

                    b.ToTable("warehouse_zones", (string)null);
                });

            modelBuilder.Entity("SmartFactory.Api.Models.Database.AiRecommendationEntity", b =>
                {
                    b.HasOne("SmartFactory.Api.Models.Database.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("ReviewedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_ai_recommendations_users_reviewed_by");
                });

            modelBuilder.Entity("SmartFactory.Api.Models.Database.AiRecommendationLinkEntity", b =>
                {
                    b.HasOne("SmartFactory.Api.Models.Database.AiRecommendationEntity", null)
                        .WithMany()
                        .HasForeignKey("RecommendationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ai_recommendation_links_ai_recommendations_recommendation_id");
                });

            modelBuilder.Entity("SmartFactory.Api.Models.Database.CameraEntity", b =>
                {
                    b.HasOne("SmartFactory.Api.Models.Database.FactoryAreaEntity", null)
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cameras_factory_areas_area_id");
                });

            modelBuilder.Entity("SmartFactory.Api.Models.Database.CameraEventEntity", b =>
                {
                    b.HasOne("SmartFactory.Api.Models.Database.FactoryAreaEntity", null)
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_camera_events_factory_areas_area_id");

                    b.HasOne("SmartFactory.Api.Models.Database.SafetyAlertEntity", null)
                        .WithMany()
                        .HasForeignKey("RelatedAlertId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_camera_events_safety_alerts_related_alert_id");
                });

            modelBuilder.Entity("SmartFactory.Api.Models.Database.EmployeeEntity", b =>
                {
                    b.HasOne("SmartFactory.Api.Models.Database.ProductionLineEntity", null)
                        .WithMany()
                        .HasForeignKey("CurrentLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_employees_production_lines_current_line_id");
                });

            modelBuilder.Entity("SmartFactory.Api.Models.Database.EmployeeSkillEntity", b =>
                {
                    b.HasOne("SmartFactory.Api.Models.Database.EmployeeEntity", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_employee_skills_employees_employee_id");

                    b.HasOne("SmartFactory.Api.Models.Database.SkillEntity", null)
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_employee_skills_skills_skill_id");
                });

            modelBuilder.Entity("SmartFactory.Api.Models.Database.FormApprovalStepEntity", b =>
                {
                    b.HasOne("SmartFactory.Api.Models.Database.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("ApproverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_form_approval_steps_users_approver_id");

                    b.HasOne("SmartFactory.Api.Models.Database.FormRequestEntity", null)
                        .WithMany()
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_form_approval_steps_form_requests_form_id");
                });

            modelBuilder.Entity("SmartFactory.Api.Models.Database.FormRequestEntity", b =>
                {
                    b.HasOne("SmartFactory.Api.Models.Database.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("ApproverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_form_requests_users_approver_id");

                    b.HasOne("SmartFactory.Api.Models.Database.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_form_requests_users_requester_id");
                });

            modelBuilder.Entity("SmartFactory.Api.Models.Database.GoodsMovementEntity", b =>
                {
                    b.HasOne("SmartFactory.Api.Models.Database.WarehouseZoneEntity", null)
                        .WithMany()
                        .HasForeignKey("FromZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_goods_movements_warehouse_zones_from_zone_id");

                    b.HasOne("SmartFactory.Api.Models.Database.WarehouseItemEntity", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_goods_movements_warehouse_items_item_id");

                    b.HasOne("SmartFactory.Api.Models.Database.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("MovedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_goods_movements_users_moved_by");

                    b.HasOne("SmartFactory.Api.Models.Database.WarehouseZoneEntity", null)
                        .WithMany()
                        .HasForeignKey("ToZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_goods_movements_warehouse_zones_to_zone_id");
                });

            modelBuilder.Entity("SmartFactory.Api.Models.Database.IoMasterEntity", b =>
                {
                    b.HasOne("SmartFactory.Api.Models.Database.BusinessUnitEntity", null)
                        .WithMany()
                        .HasForeignKey("BuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_io_masters_business_units_bu_id");
                });

            modelBuilder.Entity("SmartFactory.Api.Models.Database.MachineEntity", b =>
                {
                    b.HasOne("SmartFactory.Api.Models.Database.ProductionLineEntity", null)
                        .WithMany()
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_machines_production_lines_line_id");
                });

            modelBuilder.Entity("SmartFactory.Api.Models.Database.MachineIssueEntity", b =>
                {
                    b.HasOne("SmartFactory.Api.Models.Database.ProductionLineEntity", null)
                        .WithMany()
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_machine_issues_production_lines_line_id");

                    b.HasOne("SmartFactory.Api.Models.Database.MachineEntity", null)
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_machine_issues_machines_machine_id");

                    b.HasOne("SmartFactory.Api.Models.Database.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("ReportedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_machine_issues_users_reported_by");
                });

            modelBuilder.Entity("SmartFactory.Api.Models.Database.NotificationEntity", b =>
                {
                    b.HasOne("SmartFactory.Api.Models.Database.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_target_user_id");
                });

            modelBuilder.Entity("SmartFactory.Api.Models.Database.NotificationLinkEntity", b =>
                {
                    b.HasOne("SmartFactory.Api.Models.Database.NotificationEntity", null)
                        .WithMany()
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_notification_links_notifications_notification_id");
                });

            modelBuilder.Entity("SmartFactory.Api.Models.Database.ProductionLineEntity", b =>
                {
                    b.HasOne("SmartFactory.Api.Models.Database.FactoryAreaEntity", null)
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_production_lines_factory_areas_area_id");
                });

            modelBuilder.Entity("SmartFactory.Api.Models.Database.ProductionRecordEntity", b =>
                {
                    b.HasOne("SmartFactory.Api.Models.Database.ProductionLineEntity", null)
                        .WithMany()
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_production_records_production_lines_line_id");
                });

            modelBuilder.Entity("SmartFactory.Api.Models.Database.ReportEntity", b =>
                {
                    b.HasOne("SmartFactory.Api.Models.Database.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reports_users_created_by");
                });

            modelBuilder.Entity("SmartFactory.Api.Models.Database.ReportSourceLinkEntity", b =>
                {
                    b.HasOne("SmartFactory.Api.Models.Database.ReportEntity", null)
                        .WithMany()
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_report_source_links_reports_report_id");
                });

            modelBuilder.Entity("SmartFactory.Api.Models.Database.RolePermissionEntity", b =>
                {
                    b.HasOne("SmartFactory.Api.Models.Database.PermissionEntity", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permissions_permission_id");

                    b.HasOne("SmartFactory.Api.Models.Database.RoleEntity", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_roles_role_id");
                });

            modelBuilder.Entity("SmartFactory.Api.Models.Database.SafetyAlertCameraEventEntity", b =>
                {
                    b.HasOne("SmartFactory.Api.Models.Database.SafetyAlertEntity", null)
                        .WithMany()
                        .HasForeignKey("AlertId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_safety_alert_camera_events_safety_alerts_alert_id");

                    b.HasOne("SmartFactory.Api.Models.Database.CameraEventEntity", null)
                        .WithMany()
                        .HasForeignKey("CameraEventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_safety_alert_camera_events_camera_events_camera_event_id");
                });

            modelBuilder.Entity("SmartFactory.Api.Models.Database.SafetyAlertEntity", b =>
                {
                    b.HasOne("SmartFactory.Api.Models.Database.FactoryAreaEntity", null)
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_safety_alerts_factory_areas_area_id");

                    b.HasOne("SmartFactory.Api.Models.Database.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("AssignedTo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_safety_alerts_users_assigned_to");
                });

            modelBuilder.Entity("SmartFactory.Api.Models.Database.ShiftPlanAssignmentEntity", b =>
                {
                    b.HasOne("SmartFactory.Api.Models.Database.EmployeeEntity", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_shift_plan_assignments_employees_employee_id");

                    b.HasOne("SmartFactory.Api.Models.Database.ShiftPlanEntity", null)
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_shift_plan_assignments_shift_plans_shift_id");
                });

            modelBuilder.Entity("SmartFactory.Api.Models.Database.ShiftPlanEntity", b =>
                {
                    b.HasOne("SmartFactory.Api.Models.Database.ProductionLineEntity", null)
                        .WithMany()
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_shift_plans_production_lines_line_id");
                });

            modelBuilder.Entity("SmartFactory.Api.Models.Database.UserEntity", b =>
                {
                    b.HasOne("SmartFactory.Api.Models.Database.RoleEntity", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_roles_role_id");
                });

            modelBuilder.Entity("SmartFactory.Api.Models.Database.WarehouseItemEntity", b =>
                {
                    b.HasOne("SmartFactory.Api.Models.Database.WarehouseZoneEntity", null)
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_warehouse_items_warehouse_zones_zone_id");
                });

            modelBuilder.Entity("SmartFactory.Api.Models.Database.WarehouseItemIoLinkEntity", b =>
                {
                    b.HasOne("SmartFactory.Api.Models.Database.IoMasterEntity", null)
                        .WithMany()
                        .HasForeignKey("IoMasterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_warehouse_item_io_links_io_masters_io_master_id");

                    b.HasOne("SmartFactory.Api.Models.Database.WarehouseItemEntity", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_warehouse_item_io_links_warehouse_items_item_id");
                });
#pragma warning restore 612, 618
        }
    }
}
