using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using SmartFactory.Api.Models;

namespace SmartFactory.Api.Documents;

/// <summary>
/// Renders an electronic form request into a printable PDF request form.
/// Pure code (QuestPDF) — the form data fills a fixed document layout; no external
/// service is involved.
/// </summary>
public static class FormPdfDocument
{
    public static byte[] Generate(FormRequestDto form, DateTime generatedAt)
    {
        return Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(2, Unit.Centimetre);
                page.DefaultTextStyle(x => x.FontSize(11).FontFamily("Arial").FontColor("#1f2a37"));

                page.Header().Element(c => Header(c, form));
                page.Content().Element(c => Body(c, form));
                page.Footer().Element(c => Footer(c, generatedAt));
            });
        }).GeneratePdf();
    }

    private static void Header(IContainer container, FormRequestDto form)
    {
        container.Column(col =>
        {
            col.Item().Row(row =>
            {
                row.RelativeItem().Column(c =>
                {
                    c.Item().Text("SMART FACTORY").FontSize(20).Bold().FontColor("#2563eb");
                    c.Item().Text("AI Operations Dashboard").FontSize(10).FontColor("#64748b");
                });
                row.RelativeItem().Column(c =>
                {
                    c.Item().AlignRight().Text($"No: {form.Id}").FontSize(10);
                    c.Item().AlignRight().Text("Electronic request form").FontSize(10).FontColor("#64748b");
                });
            });
            col.Item().PaddingTop(10).LineHorizontal(2).LineColor("#2563eb");
        });
    }

    private static void Body(IContainer container, FormRequestDto form)
    {
        container.PaddingVertical(22).Column(col =>
        {
            col.Spacing(20);

            col.Item().Text("REQUEST FORM").FontSize(18).Bold().AlignCenter().FontColor("#0f172a");

            col.Item().Table(table =>
            {
                table.ColumnsDefinition(c =>
                {
                    c.ConstantColumn(120);
                    c.RelativeColumn();
                    c.ConstantColumn(120);
                    c.RelativeColumn();
                });

                void Field(string label, string value)
                {
                    table.Cell().PaddingVertical(6).Text(label).FontSize(10).FontColor("#64748b");
                    table.Cell().PaddingVertical(6).Text(value).SemiBold();
                }

                Field("Form ID", form.Id);
                Field("Type", form.FormType);
                Field("Requester", form.Requester);
                Field("Department", form.Department);
                Field("Status", form.Status);
                Field("Submitted", form.SubmittedAt);
            });

            col.Item().Column(c =>
            {
                c.Item().Text("Request details").Bold();
                c.Item().PaddingTop(6).Border(1).BorderColor("#cbd5e1").Background("#f8fafc")
                    .Padding(12).MinHeight(80).Text(form.Summary);
            });

            col.Item().PaddingTop(24).Row(row =>
            {
                row.RelativeItem().Column(Signature("Requester"));
                row.ConstantItem(50);
                row.RelativeItem().Column(Signature("Approver"));
            });
        });
    }

    private static Action<ColumnDescriptor> Signature(string role) => col =>
    {
        col.Item().AlignCenter().Text(role).Bold();
        col.Item().Height(55);
        col.Item().LineHorizontal(1).LineColor("#94a3b8");
        col.Item().AlignCenter().PaddingTop(4).Text("(Signature & full name)").FontSize(9).FontColor("#64748b");
    };

    private static void Footer(IContainer container, DateTime generatedAt)
    {
        container.Column(col =>
        {
            col.Item().PaddingBottom(6).LineHorizontal(1).LineColor("#e2e8f0");
            col.Item().Row(row =>
            {
                row.RelativeItem().Text($"Auto-generated by Smart Factory · {generatedAt:dd/MM/yyyy HH:mm}")
                    .FontSize(8).FontColor("#94a3b8");
                row.RelativeItem().AlignRight().Text(text =>
                {
                    text.DefaultTextStyle(x => x.FontSize(8).FontColor("#94a3b8"));
                    text.Span("Page ");
                    text.CurrentPageNumber();
                    text.Span(" / ");
                    text.TotalPages();
                });
            });
        });
    }
}
